services:
  elasticsearch:
    image:  prakharnag98/elasticsearch_vector:multi 
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    
    
