services:
  elasticsearch:
    image:  YOUR-DOCKERHUB-USERNAME/[REPOSITORY[:TAG]]
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    
    
