services:
  elasticsearch:
    image: prakharnag98/elasticsearch_8.12:multi
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
    ports:
      - "9200:9200"
    
    
